In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [2]:
df = pd.read_csv('C:/Users/ishan/Documents/Data Science Projects/Data Science/Deep Learning/ANN Churn Modelling/Churn_Modelling.csv')

In [3]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [5]:
X = df.iloc[:,3:13]
y= df.iloc[:,13]

In [8]:
geography = pd.get_dummies(X['Geography'], drop_first= True)
gender = pd.get_dummies(X['Gender'], drop_first= True)

In [9]:
X = pd.concat([X, geography, gender], axis = 1)
X.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Germany,Spain,Male
0,619,France,Female,42,2,0.00,1,1,1,101348.88,0,0,0
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,1,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,0,0,0
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0,0,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,1,0

In [10]:
X = X.drop(['Geography', 'Gender'] , axis = 1)
X.head()

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Germany,Spain,Male
0,619,42,2,0.00,1,1,1,101348.88,0,0,0
1,608,41,1,83807.86,1,0,1,112542.58,0,1,0
2,502,42,8,159660.80,3,1,0,113931.57,0,0,0
3,699,39,1,0.00,2,0,0,93826.63,0,0,0
4,850,43,2,125510.82,1,1,1,79084.10,0,1,0

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test =  train_test_split(X, y, test_size= 0.2, random_state= 42)

In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

In [13]:
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

ModuleNotFoundError: No module named 'keras'

In [16]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LeakyReLU, PReLU, ELU
from keras.layers import Dropout

In [26]:
classifier = Sequential()

In [27]:
# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 10, kernel_initializer = 'he_uniform',activation='relu',input_dim = 11))
classifier.add(Dropout(0.3))

# Adding the second hidden layer
classifier.add(Dense(units = 10, kernel_initializer = 'he_uniform',activation='relu'))
classifier.add(Dropout(0.3))
# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer  = 'glorot_uniform', activation = 'sigmoid'))

# Compiling the ANN
classifier.compile(optimizer = 'Adamax', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Fitting the ANN to the Training set
model_history=classifier.fit(X_train, y_train,validation_split=0.33, batch_size = 10, epochs = 100)

Epoch 1/100
536/536 [==============================] - 2s 3ms/step - loss: 0.6658 - accuracy: 0.7292 - val_loss: 0.5347 - val_accuracy: 0.7872
Epoch 2/100
536/536 [==============================] - 1s 3ms/step - loss: 0.6037 - accuracy: 0.7628 - val_loss: 0.5072 - val_accuracy: 0.7887
Epoch 3/100
536/536 [==============================] - 1s 2ms/step - loss: 0.5602 - accuracy: 0.7753 - val_loss: 0.4923 - val_accuracy: 0.7902
Epoch 4/100
536/536 [==============================] - 1s 2ms/step - loss: 0.5370 - accuracy: 0.7905 - val_loss: 0.4834 - val_accuracy: 0.7910
Epoch 5/100
536/536 [==============================] - 1s 2ms/step - loss: 0.5338 - accuracy: 0.7808 - val_loss: 0.4760 - val_accuracy: 0.7906
Epoch 6/100
536/536 [==============================] - 1s 3ms/step - loss: 0.5094 - accuracy: 0.7961 - val_loss: 0.4715 - val_accuracy: 0.7906
Epoch 7/100
536/536 [==============================] - 1s 2ms/step - loss: 0.5076 - accuracy: 0.7904 - val_loss: 0.4664 - val_accuracy: 0.7910
Epoch 8/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4865 - accuracy: 0.7949 - val_loss: 0.4631 - val_accuracy: 0.7906
Epoch 9/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4915 - accuracy: 0.7964 - val_loss: 0.4602 - val_accuracy: 0.7906
Epoch 10/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4806 - accuracy: 0.8067 - val_loss: 0.4578 - val_accuracy: 0.7906
Epoch 11/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4835 - accuracy: 0.7920 - val_loss: 0.4548 - val_accuracy: 0.7910
Epoch 12/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4753 - accuracy: 0.8038 - val_loss: 0.4528 - val_accuracy: 0.7910
Epoch 13/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4808 - accuracy: 0.7977 - val_loss: 0.4513 - val_accuracy: 0.7910
Epoch 14/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4803 - accuracy: 0.7927 - val_loss: 0.4505 - val_accuracy: 0.7910
Epoch 15/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4707 - accuracy: 0.8007 - val_loss: 0.4488 - val_accuracy: 0.7917
Epoch 16/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4738 - accuracy: 0.8057 - val_loss: 0.4470 - val_accuracy: 0.7917
Epoch 17/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4654 - accuracy: 0.8020 - val_loss: 0.4453 - val_accuracy: 0.7914
Epoch 18/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4521 - accuracy: 0.8110 - val_loss: 0.4443 - val_accuracy: 0.7917
Epoch 19/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4495 - accuracy: 0.8055 - val_loss: 0.4430 - val_accuracy: 0.7929
Epoch 20/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4434 - accuracy: 0.8131 - val_loss: 0.4413 - val_accuracy: 0.7970
Epoch 21/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4555 - accuracy: 0.8034 - val_loss: 0.4408 - val_accuracy: 0.7970
Epoch 22/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4559 - accuracy: 0.8048 - val_loss: 0.4407 - val_accuracy: 0.7967
Epoch 23/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4524 - accuracy: 0.8070 - val_loss: 0.4397 - val_accuracy: 0.7978
Epoch 24/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4661 - accuracy: 0.7983 - val_loss: 0.4392 - val_accuracy: 0.7986
Epoch 25/100
536/536 [==============================] - 1s 3ms/step - loss: 0.4650 - accuracy: 0.8055 - val_loss: 0.4383 - val_accuracy: 0.8008
Epoch 26/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4620 - accuracy: 0.8010 - val_loss: 0.4380 - val_accuracy: 0.8005
Epoch 27/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4484 - accuracy: 0.8077 - val_loss: 0.4376 - val_accuracy: 0.8023
Epoch 28/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4367 - accuracy: 0.8169 - val_loss: 0.4369 - val_accuracy: 0.8046
Epoch 29/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4551 - accuracy: 0.8013 - val_loss: 0.4370 - val_accuracy: 0.8020
Epoch 30/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4635 - accuracy: 0.8027 - val_loss: 0.4358 - val_accuracy: 0.8058
Epoch 31/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4371 - accuracy: 0.8160 - val_loss: 0.4356 - val_accuracy: 0.8054
Epoch 32/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4423 - accuracy: 0.8140 - val_loss: 0.4353 - val_accuracy: 0.8054
Epoch 33/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4558 - accuracy: 0.8024 - val_loss: 0.4350 - val_accuracy: 0.8061
Epoch 34/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4338 - accuracy: 0.8093 - val_loss: 0.4345 - val_accuracy: 0.8065
Epoch 35/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4505 - accuracy: 0.8051 - val_loss: 0.4346 - val_accuracy: 0.8058
Epoch 36/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4415 - accuracy: 0.8066 - val_loss: 0.4343 - val_accuracy: 0.8061
Epoch 37/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4397 - accuracy: 0.8088 - val_loss: 0.4334 - val_accuracy: 0.8084
Epoch 38/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4476 - accuracy: 0.8120 - val_loss: 0.4330 - val_accuracy: 0.8088
Epoch 39/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4693 - accuracy: 0.7939 - val_loss: 0.4326 - val_accuracy: 0.8095
Epoch 40/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4335 - accuracy: 0.8141 - val_loss: 0.4321 - val_accuracy: 0.8107
Epoch 41/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4465 - accuracy: 0.8145 - val_loss: 0.4313 - val_accuracy: 0.8148
Epoch 42/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4516 - accuracy: 0.8031 - val_loss: 0.4314 - val_accuracy: 0.8114
Epoch 43/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4352 - accuracy: 0.8044 - val_loss: 0.4306 - val_accuracy: 0.8148
Epoch 44/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4377 - accuracy: 0.8108 - val_loss: 0.4300 - val_accuracy: 0.8164
Epoch 45/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4488 - accuracy: 0.8045 - val_loss: 0.4293 - val_accuracy: 0.8167
Epoch 46/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4394 - accuracy: 0.8124 - val_loss: 0.4287 - val_accuracy: 0.8183
Epoch 47/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4320 - accuracy: 0.8147 - val_loss: 0.4284 - val_accuracy: 0.8175
Epoch 48/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4491 - accuracy: 0.8058 - val_loss: 0.4278 - val_accuracy: 0.8194
Epoch 49/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4338 - accuracy: 0.8102 - val_loss: 0.4277 - val_accuracy: 0.8190
Epoch 50/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4270 - accuracy: 0.8182 - val_loss: 0.4271 - val_accuracy: 0.8201
Epoch 51/100
536/536 [==============================] - 1s 3ms/step - loss: 0.4373 - accuracy: 0.8125 - val_loss: 0.4261 - val_accuracy: 0.8198
Epoch 52/100
536/536 [==============================] - 1s 3ms/step - loss: 0.4476 - accuracy: 0.8086 - val_loss: 0.4258 - val_accuracy: 0.8220
Epoch 53/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4241 - accuracy: 0.8156 - val_loss: 0.4246 - val_accuracy: 0.8213
Epoch 54/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4277 - accuracy: 0.8182 - val_loss: 0.4237 - val_accuracy: 0.8247
Epoch 55/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4453 - accuracy: 0.8090 - val_loss: 0.4238 - val_accuracy: 0.8258
Epoch 56/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4262 - accuracy: 0.8163 - val_loss: 0.4230 - val_accuracy: 0.8270
Epoch 57/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4248 - accuracy: 0.8145 - val_loss: 0.4231 - val_accuracy: 0.8258

Epoch 58/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4204 - accuracy: 0.8217 - val_loss: 0.4218 - val_accuracy: 0.8289
Epoch 59/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4188 - accuracy: 0.8150 - val_loss: 0.4217 - val_accuracy: 0.8289
Epoch 60/100
536/536 [==============================] - 1s 3ms/step - loss: 0.4067 - accuracy: 0.8306 - val_loss: 0.4208 - val_accuracy: 0.8304
Epoch 61/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4206 - accuracy: 0.8197 - val_loss: 0.4197 - val_accuracy: 0.8296
Epoch 62/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4316 - accuracy: 0.8098 - val_loss: 0.4197 - val_accuracy: 0.8300
Epoch 63/100
536/536 [==============================] - 1s 3ms/step - loss: 0.4190 - accuracy: 0.8144 - val_loss: 0.4184 - val_accuracy: 0.8292
Epoch 64/100
536/536 [==============================] - 1s 3ms/step - loss: 0.4234 - accuracy: 0.8159 - val_loss: 0.4181 - val_accuracy: 0.8300
Epoch 65/100
536/536 [==============================] - 2s 3ms/step - loss: 0.4291 - accuracy: 0.8113 - val_loss: 0.4177 - val_accuracy: 0.8296
Epoch 66/100
536/536 [==============================] - 1s 3ms/step - loss: 0.4196 - accuracy: 0.8193 - val_loss: 0.4166 - val_accuracy: 0.8292
Epoch 67/100
536/536 [==============================] - 1s 3ms/step - loss: 0.4295 - accuracy: 0.8103 - val_loss: 0.4156 - val_accuracy: 0.8315
Epoch 68/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4274 - accuracy: 0.8189 - val_loss: 0.4143 - val_accuracy: 0.8307
Epoch 69/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4196 - accuracy: 0.8289 - val_loss: 0.4131 - val_accuracy: 0.8315
Epoch 70/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4257 - accuracy: 0.8174 - val_loss: 0.4133 - val_accuracy: 0.8315
Epoch 71/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4201 - accuracy: 0.8193 - val_loss: 0.4125 - val_accuracy: 0.8326
Epoch 72/100
536/536 [==============================] - 1s 3ms/step - loss: 0.4116 - accuracy: 0.8283 - val_loss: 0.4113 - val_accuracy: 0.8319
Epoch 73/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4137 - accuracy: 0.8257 - val_loss: 0.4101 - val_accuracy: 0.8315
Epoch 74/100
536/536 [==============================] - 2s 3ms/step - loss: 0.4090 - accuracy: 0.8212 - val_loss: 0.4097 - val_accuracy: 0.8315
Epoch 75/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4050 - accuracy: 0.8261 - val_loss: 0.4094 - val_accuracy: 0.8311
Epoch 76/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4182 - accuracy: 0.8222 - val_loss: 0.4086 - val_accuracy: 0.8334
Epoch 77/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4160 - accuracy: 0.8188 - val_loss: 0.4083 - val_accuracy: 0.8319
Epoch 78/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4017 - accuracy: 0.8320 - val_loss: 0.4079 - val_accuracy: 0.8326
Epoch 79/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4253 - accuracy: 0.8221 - val_loss: 0.4072 - val_accuracy: 0.8326
Epoch 80/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4196 - accuracy: 0.8202 - val_loss: 0.4076 - val_accuracy: 0.8330
Epoch 81/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4081 - accuracy: 0.8264 - val_loss: 0.4068 - val_accuracy: 0.8323
Epoch 82/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4151 - accuracy: 0.8315 - val_loss: 0.4067 - val_accuracy: 0.8315
Epoch 83/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4094 - accuracy: 0.8306 - val_loss: 0.4056 - val_accuracy: 0.8330
Epoch 84/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4213 - accuracy: 0.8159 - val_loss: 0.4056 - val_accuracy: 0.8319
Epoch 85/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4180 - accuracy: 0.8241 - val_loss: 0.4050 - val_accuracy: 0.8315
Epoch 86/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4154 - accuracy: 0.8195 - val_loss: 0.4052 - val_accuracy: 0.8319
Epoch 87/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4113 - accuracy: 0.8197 - val_loss: 0.4044 - val_accuracy: 0.8326
Epoch 88/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4135 - accuracy: 0.8243 - val_loss: 0.4039 - val_accuracy: 0.8342
Epoch 89/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4222 - accuracy: 0.8133 - val_loss: 0.4035 - val_accuracy: 0.8349
Epoch 90/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4003 - accuracy: 0.8335 - val_loss: 0.4031 - val_accuracy: 0.8349
Epoch 91/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4128 - accuracy: 0.8253 - val_loss: 0.4028 - val_accuracy: 0.8342
Epoch 92/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4099 - accuracy: 0.8292 - val_loss: 0.4023 - val_accuracy: 0.8334
Epoch 93/100
536/536 [==============================] - 1s 3ms/step - loss: 0.4020 - accuracy: 0.8318 - val_loss: 0.4024 - val_accuracy: 0.8345
Epoch 94/100
536/536 [==============================] - 1s 3ms/step - loss: 0.4104 - accuracy: 0.8265 - val_loss: 0.4023 - val_accuracy: 0.8345
Epoch 95/100
536/536 [==============================] - 1s 3ms/step - loss: 0.4162 - accuracy: 0.8214 - val_loss: 0.4018 - val_accuracy: 0.8345
Epoch 96/100
536/536 [==============================] - 1s 2ms/step - loss: 0.4131 - accuracy: 0.8267 - val_loss: 0.4011 - val_accuracy: 0.8342
Epoch 97/100
536/536 [==============================] - 1s 3ms/step - loss: 0.4045 - accuracy: 0.8236 - val_loss: 0.4014 - val_accuracy: 0.8360
Epoch 98/100
536/536 [==============================] - 2s 3ms/step - loss: 0.4110 - accuracy: 0.8245 - val_loss: 0.4008 - val_accuracy: 0.8368
Epoch 99/100
536/536 [==============================] - 1s 3ms/step - loss: 0.3887 - accuracy: 0.8424 - val_loss: 0.4002 - val_accuracy: 0.8353
Epoch 100/100
536/536 [==============================] - 1s 3ms/step - loss: 0.4115 - accuracy: 0.8237 - val_loss: 0.3993 - val_accuracy: 0.8342

In [28]:
y_pred = classifier.predict(X_test)
y_pred

array([[0.07368463],
       [0.06470484],
       [0.26559013],
       ...,
       [0.5769693 ],
       [0.10146669],
       [0.2654347 ]], dtype=float32)

In [29]:
y_pred = (y_pred > 0.5)
y_pred

array([[False],
       [False],
       [False],
       ...,
       [ True],
       [False],
       [False]])

In [23]:
y_test

6252    0
4684    0
1731    0
4742    0
4521    0
       ..
6412    1
8285    0
7853    1
1095    1
6929    1
Name: Exited, Length: 2000, dtype: int64

In [30]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[1583,   24],
       [ 279,  114]], dtype=int64)

In [31]:
# Calculate the Accuracy
from sklearn.metrics import accuracy_score
score=accuracy_score(y_pred,y_test)
score

# We got accuracy of 0.85 when we didn't used Dropout
# We got accuracy of 0.8485 when we used Dropout

0.8485